package report

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

var requiredFiles = []string{
	"capacity.csv",
	"summary.csv",
	"profiles.csv",
}

func DefaultPublishDest(root string) string {
	stamp := time.Now().UTC().Format("2006-01-02-canonical-150405Z")
	return filepath.Join(root, "docs", "measurements", stamp)
}

func Publish(runDir, dest, currentMD, root string) error {
	for _, name := range requiredFiles {
		if _, err := os.Stat(filepath.Join(runDir, name)); err != nil {
			return fmt.Errorf("%s is missing: %s", runDir, name)
		}
	}

	if err := os.MkdirAll(dest, 0755); err != nil {
		return err
	}

	for _, name := range requiredFiles {
		data, err := os.ReadFile(filepath.Join(runDir, name))
		if err != nil {
			return err
		}
		text := strings.ReplaceAll(string(data), "\r\n", "\n")
		text = strings.ReplaceAll(text, "\r", "\n")
		if err := os.WriteFile(filepath.Join(dest, name), []byte(text), 0644); err != nil {
			return err
		}
	}

	plots := filepath.Join(dest, "plots")
	os.RemoveAll(plots)
	reportPath := filepath.Join(dest, "report.md")
	os.Remove(reportPath)

	label := relFromRoot(dest, root) + " (published from " + relFromRoot(runDir, root) + ")"
	if err := Render(dest, reportPath, "", label); err != nil {
		return fmt.Errorf("render report: %w", err)
	}

	if err := writeCurrentPointer(currentMD, dest, runDir, root); err != nil {
		return fmt.Errorf("write current.md: %w", err)
	}

	fmt.Println("published canonical result to", dest)
	fmt.Println("updated current pointer:", currentMD)
	fmt.Println("current report:", reportPath)
	return nil
}

func writeCurrentPointer(currentMD, dest, runDir, root string) error {
	dir := filepath.Dir(currentMD)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	reportRel := markdownRel(filepath.Join(dest, "report.md"), dir)
	capacityRel := markdownRel(filepath.Join(dest, "capacity.csv"), dir)
	sourceRel := relFromRoot(runDir, root)

	content := strings.Join([]string{
		"# Current Canonical Measurement",
		"",
		fmt.Sprintf("Open: [`%s`](%s)", reportRel, reportRel),
		"",
		fmt.Sprintf("Capacity data: [`%s`](%s)", capacityRel, capacityRel),
		"",
		fmt.Sprintf("Published from: `%s`", sourceRel),
		"",
		"This file is generated by `rudp-benchctl`.",
		"",
	}, "\n")

	return os.WriteFile(currentMD, []byte(content), 0644)
}

func relFromRoot(path, root string) string {
	abs, err := filepath.Abs(path)
	if err != nil {
		return path
	}
	rootAbs, err := filepath.Abs(root)
	if err != nil {
		return path
	}
	rel, err := filepath.Rel(rootAbs, abs)
	if err != nil {
		return path
	}
	return filepath.ToSlash(rel)
}

func markdownRel(target, from string) string {
	abs, err := filepath.Abs(target)
	if err != nil {
		return target
	}
	fromAbs, err := filepath.Abs(from)
	if err != nil {
		return target
	}
	rel, err := filepath.Rel(fromAbs, abs)
	if err != nil {
		return target
	}
	return filepath.ToSlash(rel)
}
